apisix:
  node_listen: 8080
  enable_admin: true
  admin_listen: 9180
  router:
    http: 'radixtree_uri'

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    enable_admin_ui: true 
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: admin
        role: admin
        key: "edd1c9f034335f136f87ad84b625c8f1" 

  etcd:
    host:
      - "http://etcd:2379"

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

# nginx_config:
#   http:
#     large_client_header_buffers: 4 16k
#     client_header_buffer_size: 1k   
#     client_max_body_size: 20m